version: '3.1'

services:
  database:
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRESQL_DATABASE: ead-authuser
      POSTGRESQL_PASSWORD: authuser
    ports:
      - 5432:5432  
